name = "MetadataArrays"
uuid = "49441bc9-da82-574f-b07c-a0d10dd4ac13"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>", "Zachary P. Christensen <zchristensen7@gmail.com>"]
version = "0.2"

[deps]
ArrayInterfaceCore = "30b0a656-2188-435a-8636-2ec0e6a096e2"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ArrayInterfaceCore = "0.1"
DataAPI = "1.12"
julia = "1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
