name = "MetadataArrays"
uuid = "49441bc9-da82-574f-b07c-a0d10dd4ac13"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>", "Zachary P. Christensen <zchristensen7@gmail.com>"]
version = "0.2.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[extensions]
MetadataArraysAdapt = "Adapt"

[compat]
ArrayInterface = "7"
Adapt = "4"
Aqua = "0.8"
DataAPI = "1.14"
LinearAlgebra = "1"
Statistics = "1"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ArrayInterface", "Test"]
